services:
  node-app:
    build: . # já vai pegar o Dockerfile que está no mesmo projeto do compose
    ports:
      - "3000:3000" # <porta_externa>:<porta:interna>
    volumes:
      - ./:/app # <caminho_local>:<caminho_container>
      - /app/node_modules # volume próprio para o node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
  mongo:
    image: mongo # pega imagem pronta do site docker hub
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db # nome caminho da pasta maquina host:caminho do banco mongo no container
  # redis:

volumes:
  mongo-db:
